# Generated by Django 4.1.7 on 2023-12-22 16:09

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Page_Name', models.CharField(choices=[('Home', 'Home'), ('Design Gallery', 'Design Gallery'), ('Moduler Kitchen', 'Moduler Kitchen'), ('Wordrobe Designs', 'Wordrobe Designs'), ('Vanity Unit Design', 'Vanity Unit Design'), ('Bar kitchen Designs', 'Bar kitchen Designs')], max_length=255, unique=True)),
                ('Image', models.ImageField(upload_to='Banner')),
                ('Title', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='DemoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Moduler Kitchen Designs', 'Moduler Kitchen Designs'), ('Wordrobe Designs', 'Wordrobe Designs'), ('Vanity Unit Design', 'Vanity Unit Design'), ('Bar kitchen Designs', 'Bar kitchen Designs')], max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Catagory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Verantes Kitchen Range', 'Verantes Kitchen Range'), ('Shutter Finishes', 'Shutter Finishes'), ('Handles', 'Handles'), ('Countertops and Backsplashes', 'Countertops and Backsplashes'), ('Cabinate and Hardware', 'Cabinate and Hardware'), ('Appliances', 'Appliances'), ('Sink and Faucets', 'Sink and Faucets'), ('Verantes wordrobe range', 'Verantes wordrobe range'), ('Wordrobe for Everyone', 'Wordrobe for Everyone'), ('Types of Wardrobes', 'Types of Wardrobes'), ('Wardrobe Shutter Types', 'Wardrobe Shutter Types'), ('The Cabinets', 'The Cabinets'), ('Add-ons', 'Add-ons'), ('Accessories', 'Accessories'), ('The Vanity Units Range', 'The Vanity Units Range'), ('Open Storage', 'Open Storage'), ('shedule meeting', 'shedule meeting')], max_length=255)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Showcase.product')),
            ],
        ),
        migrations.CreateModel(
            name='All_Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Image', models.ImageField(upload_to='Products')),
                ('Title', models.CharField(max_length=60)),
                ('Description', tinymce.models.HTMLField(max_length=200)),
                ('Add_On_Home_Page', models.BooleanField(default=False)),
                ('Add_On_Gallery', models.BooleanField(default=False)),
                ('catogory', smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='product', chained_model_field='product', default=None, on_delete=django.db.models.deletion.CASCADE, to='Showcase.catagory')),
                ('product', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Showcase.product')),
            ],
        ),
    ]
