# Generated by Django 4.1.7 on 2023-12-23 06:12

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('Showcase', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Image', models.ImageField(upload_to='Testimonials')),
                ('Subtitle', models.CharField(max_length=60)),
                ('Review', tinymce.models.HTMLField(max_length=200)),
            ],
        ),
    ]
