# Generated by Django 4.1.7 on 2023-12-23 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Showcase', '0002_testimonials'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonials',
            name='Name',
            field=models.CharField(default=None, max_length=40),
        ),
    ]
