# Generated by Django 4.1.7 on 2024-01-08 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Showcase', '0008_alter_product_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Image',
            field=models.ImageField(blank=True, null=True, upload_to='Catagories'),
        ),
        migrations.AddField(
            model_name='product',
            name='Link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
