# Generated by Django 4.1.7 on 2024-01-08 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Showcase', '0009_product_image_product_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Image',
            field=models.ImageField(null=True, upload_to='Catagories'),
        ),
        migrations.AlterField(
            model_name='product',
            name='Link',
            field=models.URLField(null=True),
        ),
    ]
