# Generated by Django 4.1.7 on 2023-12-22 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer_Detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Email', models.EmailField(max_length=254)),
                ('Phone_Number', models.CharField(max_length=12)),
                ('City', models.CharField(max_length=50)),
                ('Looking_For', models.CharField(max_length=50)),
                ('Budget', models.CharField(max_length=50)),
            ],
        ),
    ]
