# Generated by Django 4.1.7 on 2023-12-29 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer_Requirement', '0004_profile_whatsapp_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='whatsapp_status',
            field=models.CharField(max_length=10),
        ),
    ]
