# Generated by Django 4.1.7 on 2023-12-29 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Customer_Requirement', '0005_alter_profile_whatsapp_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='otp',
        ),
    ]
